const { Router } = require("express");
const authRoutes=require("./auth.routes");
const userRoutes=require("./user.routes");
const customerRoutes=require("./customer.routes");
const categoryRoutes=require("./category.routes");
const productRoutes=require("./product.routes");
const orderRoutes=require("./order.routes");
const dashboardRoutes=require("./dashboard.routes");
const reportRoutes=require("./report.routes");
const router=Router();

router.use("/auth",authRoutes);
router.use("/users",userRoutes);
router.use("/customers",customerRoutes);
router.use("/categories",categoryRoutes);
router.use("/products",productRoutes);
router.use("/orders",orderRoutes);
router.use("/dashboard",dashboardRoutes);
router.use("/reports",reportRoutes);
module.exports=router;